### ISSUE TITLE
Rework storage.md

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#101]
Storage page contains obsolete information that needs to be updated.

Steps we need to do

- [x] Add admonition warning of obsolete information
- [x] Add admonition notifying of planned updates (under construction)
- [x] Remove from Table of Contents/nav menu
- [x] Gather correct information together
- [x] Update page with new information

Choose your own adventure to answer "Which storage is right for me?"

1. LTS for rarely changing or immutable files that need to be retrieved many times. Write once, read many. We don't touch these. Slowest! Do not use this if IO performance is an issue. First move the data to something closer to the compute hardware.
2. $HOME and $USER_DATA for general purpose long-term storage of files that change frequently. We don't touch these.
3. $USER_SCRATCH for many and/or large temporary files lasting no longer than 30 days. Automatic rolling 30 day cleanup window. Manual cleanup as needed, possibly without warning.
4. $LOCAL_SCRATCH for modest amounts of data lasting no longer than a single job. Clean up after yourself! Will be cleaned up without warning as needed. Fastest! Use this when processing is IO bound and IO performance is critical.

**Comment by wwarriner** [comment]
As we write this page we'll need to tread carefully. Different software and hardware report the same quantities differently for different reasons.

`ls`, `du` and `rclone` all report using binary byte units by default when they aren't reporting total bytes, e.g. when the `--human-readable` flag is used.

`ls` and `du` have a `--si` flag that reports using SI byte units. `rclone` also does not have this flag, though it has come up on their issue tracker now and again. See [here](https://github.com/rclone/rclone/pull/5087) for a related pull request.

I'm not sure yet how our quota reporting works for `/data/user` and `/data/project`, whether it is binary or SI units.

To compound the issue, we also have duplication of some of our storage locations, specifically all of `/data` and `/scratch` that causes our quota reporting to indicate double the amount of usable storage.

**Comment by wwarriner** [comment]
Related: #139

**Comment by wwarriner** [comment]
Info dump for future use with choose-your-own-adventure:

Home is part of the /data/user/ folder now, so yes that would explain things. Unfortunately that also means moving files from $HOME to $USER_DATA would not help. The fix would depend on the details of your work.

Scratch is intended for short-term files, and we have policies in place to ensure data is cleared off as it ages out, after 30 days. So if you are generating many and/or large temporary files, $USER_SCRATCH is an excellent place to store them. If you have files that only need to survive for the lifetime of a single job, then $LOCAL_SCRATCH is a great place, but we need you to be sure to clean up the files at or shortly after the end of the job.

If you have data that changes very infrequently, which you need to store for long term retrieval, we have an upcoming Long Term storage S3 service that would be perfect.

If you are working with a PI on a collaborative project, we also offer space in /data/project that can be requested by the PI. We allow 25 TB of storage by default for projects in this space. These are intended for very long-term projects or for entire labs to store and share data over the course of one or more research proposals. For shorter-term and experimental projects, we also offer 5TB of space in /data/project/sloss.

If none of the above apply, then we're going to have to find a way to clear some space, by some combination of deleting unused data, or offloading it to an external service like https://uab.app.box.com. If you have PHI data then we'll need to have a different conversation.

**Comment by bjoyce3** [comment]
Example table for storage options: https://it.hms.harvard.edu/our-services/research-computing/services/storage

**Comment by wwarriner** [comment]
I think this is pretty much done. I've got an issue for Blake's most recent suggestion apart from this one. I'm closing this.
