### ISSUE TITLE
Add hardware information to Cheaha Hardware section

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#116]
Include hardware information for each generation such as architecture, cores per node, total memory per node (removing 15-20 GB for os), etc. https://uabrc.github.io/cheaha/hardware/

**Comment by wwarriner** [comment]
From discussion in Slack, we decided that page is already there, but not super user friendly.

Changes:

- add admonitions to the page to indicate tables are horizontally scrolling
- add very detailed information about hardware as a table
- add download links for raw tables
- decrease memory by 12 GiB (all but `largemem*`)

**Comment by wwarriner** [comment]
Also for partitions and quotas, merge them the other way. Have a separate quota table with names of all associated partitions
