### ISSUE TITLE
Update XIAS account with URI examples

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#117]
Looks like we might need to give examples of what URIs to provide for the RC services in the XIAS docs so people can understand the process a little better.

Also confirm that XIAS folks don't have docs themselves.

https://uabrc.github.io/account_management/xias_users/

**Comment by wwarriner** [comment]
I was unable to find official UAB documentation on usage of XIAS. They have a Service Now page with a general introduction, but it doesn't have a great permanent link (and these things change) [here](https://uabprod.service-now.com/service_portal?id=sc_cat_item&sys_id=6c70064a37e21b4024a67c1643990e05). The links on the Service Now page point right back into XIAS, so no help there.

Googling relevant terms just comes back with our own gridwiki page for it as top hit.
