### ISSUE TITLE
Short intro to linux and basic commands

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#12]
From @mdefende 

>Can model based on Auburn's page here: https://hpc.auburn.edu/hpc/docs/hpcdocs/build/html/easley/lab.html

**Comment by wwarriner** [comment]
I think we might try linking them to here: https://swcarpentry.github.io/shell-novice/

**Comment by jgordini** [comment]
[linux_intro.md](https://github.com/uabrc/uabrc.github.io/files/8164094/linux_intro.md)

Updated the Auburn docs and linked The Unix Shell document.

**Comment by jgordini** [comment]
Thats a good question. Will look into it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
