### ISSUE TITLE
Unprotected private key file 

### ISSUE THREAD

**Issue by jauperucho** [uabrc/uabrc.github.io#134]
OS: Windows + WSL:Ubuntu 20.04. I do all my CLI through Windows Terminal

Every time I download a private key file using "Basic Security Setup" Guide, I get a "warning: protected private key file" warning.
Summary and solution can be found through this [link](https://www.howtogeek.com/168119/fixing-warning-unprotected-private-key-file-on-linux/)
Note, on this link, it is more catering to git ssh with the id_rsa/id_rsa.pub, but the same principles also apply to *.pem keys

**Comment by wwarriner** [comment]
Will be resolved with #142
