### ISSUE TITLE
Suggest link to Data Management > File Transfers link at the end of the UAB Cloud > Basic Instance Setup page

### ISSUE THREAD

**Issue by jauperucho** [uabrc/uabrc.github.io#136]
It was not immediately obvious that there is a tutorial for file transfers under Data Management > File Transfer after setting up an instanc e with the guide. Left my head scratching a bit. A link to the File Transfers would be quite convenient for users not familiar with remote computing

**Comment by wwarriner** [comment]
Going to fix this one along with #138
