### ISSUE TITLE
Suggest documentation for scp & sftp file transfers 

### ISSUE THREAD

**Issue by jauperucho** [uabrc/uabrc.github.io#138]
Disclaimer: I am not fond of using GUI-based file transfer methods, so I prefer CLI utilities. I also have not tried these on Cheaha, only on Cloud.RC

Might be helpful for users to know about CLI file transfer utilities (maybe include these as footnotes in the tutorials?). SCP is particularly useful for automated analysis workflows (since it is non-interactive), and CLI SFTP is the natural first step for users that wnat to transition away from GUI file transfer utilities (eg. FileZilla) 

**SFTP**: As a primer, I like the this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-sftp-to-securely-transfer-files-with-a-remote-server). But to actually initiate an SFTP connection and pass the private key you would need this command [link](https://superuser.com/questions/483593/how-do-i-use-my-keyfile-to-sftp-transfer-data-from-one-server-to-another)
`sftp -o "IdentityFile=<path_to_key/key_name> <user>@<floating_ip>` 
**SCP**: has the same syntax as ssh
`scp -i <path_to_key/key_name> <path_to_source/source_file> <user>@<floating_ip>:<path_to_target/target_file>`
Note: "-r" flag for directories

**Comment by wwarriner** [comment]
Related to #154
