### ISSUE TITLE
cloud.rc clarifications on pem files

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#142]
Several small snags have snowballed from the security and instances pages for cloud.rc

For page https://uabrc.github.io/uab_cloud/security_setup_basic/#creating-a-key-pair

- Use pregenerated keypair (*.pem file). These are our current instructions. Add the following info for adding the generated private key.

```shell
eval `ssh-agent`
ssh-add file.pem
```
 
- Upload own keypair (more advanced). Need to run through these instructions ourselves to see all the details.

For both

- Add instructions on modifying ssh-config file to skip need for `-i` flag.
- Point to https://uabrc.github.io/uab_cloud/instance_setup_basic/#ssh-into-the-instance
- Add note to the ssh-into-the-instance page mentioning `-i` flag and pointing back to first bullet of this list to avoid needing it.

**Comment by hardawayja** [comment]
Awesome you beat me too it!

**Comment by wwarriner** [comment]
Thanks for helping us out on this front! Keep em coming as you notice things that don't quite line up with the docs!
