### ISSUE TITLE
Incorrect color on mobile devices

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#178]
![Screenshot_20220407-182639_Firefox](https://user-images.githubusercontent.com/6930772/162335428-52f04e07-ae1b-4195-a32b-b3607777363c.jpg)

Not sure how to find the css class for this one, may differ on mobile.

**Comment by jgordini** [comment]
I belive the color resides in --md-primary-fg-color--dark
you would need to update this to #1e6b52 in extra.css
 
 You can inspect the mobile view in safari by going to 
 settings > advanced > show develop menu in menu bar
 
 then going to the developer bar and setting the user agent to Safari ios 14 - iphone

**Comment by jgordini** [comment]
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors

**Comment by wwarriner** [comment]
Confirmed fixed on my device.
