### ISSUE TITLE
Fix "chapter" TOCs in each index.md

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#19]

**Comment by mdefende** [comment]
Almost none of the index.md files are being used currently. The ToC is being generated in the mkdocs.yml file. Haven't deleted tham yet because we may want to use them as a landing page for some of the sections. Not sure yet.

**Comment by wwarriner** [comment]
The UAB Cloud index, and the Cheaha index have some value as a "choose your own adventure" starting point (they need trimming). The others not as much.
