### ISSUE TITLE
Cool technique for finding largest files/dirs on linux machine

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#198]
Not sure where to put this but the following command will find the 10 largest files/dirs recursively within a folder, sorted descending.

`sudo du -sh .[^.]* * | sort -hr | head -n10`

Ignore `sudo` if not available, e.g. on Cheaha.

**Comment by jgordini** [comment]
I like that alot. 
you might like this command as well

curl cheat.sh/du

you can also install cheat on ubuntu
sudo pip3 install cheat

It works in a similar fashion just locally. 
cheat du

**Comment by wwarriner** [comment]
I'm adding that idea to the docs page I'm developing, thanks @jgordini!

**Comment by jgordini** [comment]
Awesome!
