### ISSUE TITLE
Research Computing Marketplace

### ISSUE THREAD

**Issue by jgordini** [uabrc/uabrc.github.io#206]
https://www.uab.edu/it/home/research-computing/research-digital-marketplace

We are currently linking to the follow documentation sections

Glubus
https://uabrc.github.io/data_management/transfer/globus/
HPC and Storage
https://uabrc.github.io/data_management/storage/
HPC Open Source Software Installation
https://uabrc.github.io/cheaha/getting_started/#software
HPC Licensed Software Installation
https://uabrc.github.io/cheaha/lmod/
Open on Demand HPC
https://uabrc.github.io/cheaha/open_ondemand/ood_main/

Missing a Science DMZ page

Can update as needed :)

**Comment by wwarriner** [comment]
Thanks for making this @jgordini. The issue is now obsolete because we are using redirects internally. When/if we move pages we redirect old url to new url.

**Comment by jgordini** [comment]
No problem. Happy to help.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
