### ISSUE TITLE
Grant and Publication Resources

### ISSUE THREAD

**Issue by jgordini** [uabrc/uabrc.github.io#213]
Updating this page. 
https://www.uab.edu/it/home/research-computing/cheaha

Grant and Publicaton resources currently links here. 
https://docs.uabgrid.uab.edu/wiki/Welcome#Grant_and_Publication_Resources

Seeing if there is a new page for this.

**Comment by mdefende** [comment]
This is covered by #43 and is being worked on now

**Comment by wwarriner** [comment]
Related to #356
