### ISSUE TITLE
Tables have nans instead of empty cells

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#22]
The table importer fills blanks with "nan". Doesn't appear to be an obvious solution, and the plugin has no config for it. We may need to investigate deeper.

**Comment by mdefende** [comment]
The actual script for creating the table can be found at https://github.com/timvink/mkdocs-table-reader-plugin/blob/master/mkdocs_table_reader_plugin/plugin.py. The location where the table is converted to Markdown text and pasted into the source .md file is at the bottom of the linked script. It doesn't seem like it would be too difficult to fork the repo and add in a snippet that replaces any nan text with 3 spaces (or whatever would make the table readable, not sure.

This is potentially something to hack on a Tuesday when we aren't quite as busy

**Comment by wwarriner** [comment]
Looks like its a typical pandas issue with nans appearing. It's part of read_csv. I think we can solve this purely by modifying the `jinja` code in the markdown file. Instead of:

```jinja
{{ read_csv( file ) }}
```

We do

```jinja
{{ read_csv( file, keep_default_na=False ) }}
```

**Comment by wwarriner** [comment]
Yep worked perfectly. Putting together pull request.
