### ISSUE TITLE
Update slurm example

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#230]
Located here: https://uabrc.github.io/cheaha/slurm/sbatch_usage/

Update mem total (not per CPU), reexamine examples on the docs, slurm default discussion, how to be explicit with slurm scripts for the research community (see next bullet item as well)

**Comment by wwarriner** [comment]
To clarify, using `--mem=` instead of `--mem-per-cpu=` in the default script. When this is rewritten, go through the flags at https://slurm.schedmd.com/sbatch.html to make sure we don't miss anything helpful.

Off the top of my head:

```shell
--ntasks=
--cpus-per-task=
--mem=
--partition=
--time=
--job-name=
--output=
--error=
```

And of course some example using `--array` as well.
