### ISSUE TITLE
Command Line Help

### ISSUE THREAD

**Issue by jgordini** [uabrc/uabrc.github.io#236]
Wanted to mention this resource for command line basics. 
https://www.theodinproject.com/lessons/foundations-command-line-basics

Also the following lesson on setting up git is helpful as well. 
https://www.theodinproject.com/lessons/foundations-setting-up-git

Here is the setup video for VS Code
https://code.visualstudio.com/docs/introvideos/basics

**Comment by mdefende** [comment]
Related to #12
