### ISSUE TITLE
Add step-by-step guide to contribution workflow

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#261]
Setup:
- create and checkout branch `dev` from `main`
- Modify `.github/workflows/ci.yml` to include `dev` as a triggering branch, like the following

```yaml
on:
  push:
    branches:
      - dev  # add this line
      - main
```
- commit to `dev`
- push `dev` to your fork

Now whenever you push `dev` to your fork, it will build the docs, which will be visible at `https://<github-username>.github.io/uabrc.github.io/`

Workflow

- fetch upstream changes from [uabrc.github.io](http://uabrc.github.io/) main to my fork
- pull my fork to VS code
- create a new working branch in my fork from `main` with a name appropriate for the change I'm making
    - `feat-<name>` for features
    - `fix-<name>` for fixes
- merge working branch into `dev`
- wait for build and observe changes at `https://<github-username>.github.io/uabrc.github.io/` to ensure things worked as expected
- iterate
- when satisfied, push working branch
- create PR into upstream using working branch

**Comment by mdefende** [comment]
A step should be added after creating and working on a branch for a change or fix. In the terminal, you can build the site locally for viewing using the `mkdocs serve` command. At the very least, glaring errors can be caught this way before pushing changes to the remote `dev` branch. This introduces two times to check changes: locally before pushing and remotely in your personal fork after pushing.
