### ISSUE TITLE
Add RProjects and renv to Workflow Solutions

### ISSUE THREAD

**Issue by mdefende** [uabrc/uabrc.github.io#290]
R Projects are self-contained files and folders pertaining to a specific project a researcher is working on. These can be easily created in the RStudio interface and save environment information about the project including Git repo information to make versioning much easier (think similar to VSCode's Git interface). Projects are designed to be used with relative paths to make them more portable (i.e. up to Github and back down to a local machine or from a personal space to a project space on Cheaha). Switching between projects is as simple as clicking a dropdown menu in RStudio.

renv is a package management tool for R that behaves similarly to Anaconda. Since it isn't built directly into R and RStudio, it's not widely used by researchers. The main benefits are:

1. Control packages and versions for each project
2. Environments can be exported with version numbers and shared between researchers
3. Compatible with both CRAN and Bioconductor (highly used here) as well as some other package repos
4. Packages used across projects are not duplicated. If a package for a new project was used for an old project, a symlink will be created instead. Useful because fewer installs means fewer compilation errors and large packages not being duplicated many times across projects

**Comment by wwarriner** [comment]
This appears to exist in the docs here: https://docs.rc.uab.edu/workflow_solutions/r_environments/.
And in this PR: https://github.com/uabrc/uabrc.github.io/pull/474
Closing!
