### ISSUE TITLE
Globus: better conceptual model for how it works

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#293]
We may want to re-evaluate our docs for Globus. We have a decent how-to for using globus, but it assumes the mental model is already in a good place.

We'll need to carefully describe:

- How different endpoints can point at different physical devices (e.g. laptop vs Cheaha vs other university)
- How different endpoints can point at THE SAME physical device (e.g. Cheaha on- vs off-campus)
- How to tell which endpoints point where (open collection and look at either "owner" or "organization")
- The difference between endpoints and collections
    - Endpoints are managed using locally installed server/personal software, one per endpoint
    - Collections are managed using app.globus.org
    - Collections are subsets of endpoints, and are hosted on exactly one endpoint each
        - Files available through a collection are a subset of the host endpoint's files
        - User permissions are customizable and not limited to those available on the endpoint for access and download (but possibly for transfers, needs testing)
    - Collections behave like endpoints when using app.globus.org in terms of sharing

We'll also need documentation on using and managing collections and their permissions if we haven't already.

**Comment by bjoyce3** [comment]
+1 for this. We also have questions like how do UAB research cores and other labs set up their own endpoints to connect to ours (or ones off campus). Examples: RITM0578698

**Comment by wwarriner** [comment]
We're tackling this in a more structured fashion, and with much better understanding, here: #800
