### ISSUE TITLE
Update to LTS command list docs

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#294]
@mdefende From our meeting with the Dutta Lab. Outstanding questions about LTS we should investigate and add to the docs:

- How can I check my quota on LTS (is there a disk utility-like command?) for aws cli, s3cmd, etc
- How can I `wget` something from a remote site (off campus or 3rd party on campus) and move that to LTS? What's the command for that
- Is there a diagram to explain how people should generally use/regard LTS/central storage?

**Comment by mdefende** [comment]
Added option to check LTS usage
