### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by mdefende** [uabrc/uabrc.github.io#3]
Add FAQ entries in comments.

- [ ] Why is my job taking a while to schedule?
- [ ] Can you install this software?
- [ ] Can you create a Cheaha account for me?
- [ ] Can you create a UAB Cloud account for me?

**Comment by mdefende** [comment]
- [ ] Can you increase storage space for our project directory?

**Comment by wwarriner** [comment]
This could also take the form of a "Differential Diagnosis" for the non-specific symptoms (mostly surrounding OOD interactive job errors)

**Comment by wwarriner** [comment]
#53 is related
