### ISSUE TITLE
Move Cheaha Anaconda section

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#301]
- Move https://uabrc.github.io/cheaha/conda/ to be nested under https://uabrc.github.io/cheaha/software/software/
- Put redirect in for https://uabrc.github.io/cheaha/conda/

**Comment by wwarriner** [comment]
This issue exposed a weakness with the redirects plugin. It's not possible to use the yaml redirects file to redirect into a section.

Not allowed:

```yaml
cheaha/conda.md: cheaha/software/software.md#anaconda-on-cheaha
```

Allowed but inaccurate:

```yaml
cheaha/conda.md: cheaha/software/software.md
```

According to this issue (https://github.com/mkdocs/mkdocs-redirects/issues/16) it should be possible to work around this using a python script file.

**Comment by wwarriner** [comment]
I came up with a hacky solution based on the issue I previously linked. I'd like to see if its possible to make a pull request against the redirects plugin. It comes with facilities like validating target pages actually exist.

**Comment by wwarriner** [comment]
Ok I have maybe modified that code, need to test it does what's expected tomorrow.

**Comment by wwarriner** [comment]
Also for later, a possible way to redirect FROM an anchor link https://joomla.stackexchange.com/a/19143

**Comment by wwarriner** [comment]
Ok added a pull request to mkdocs-redirects: https://github.com/mkdocs/mkdocs-redirects/pull/42

**Comment by wwarriner** [comment]
https://github.com/mkdocs/mkdocs-redirects/releases/tag/v1.1.0

Hooray, we can move forward on this now!
