### ISSUE TITLE
Highlight the third header and fourth header in Mkdocs

### ISSUE THREAD

**Issue by Premas** [uabrc/uabrc.github.io#329]
We can highlight the third header and fourth header in Mkdocs by formatting as bold, underlining, etc.

**Comment by wwarriner** [comment]
I went ahead and revamped some overall. I find it scans better whens scrolling quickly through long pages

![image](https://user-images.githubusercontent.com/6930772/189958458-ffc27d68-8ea5-42c4-bdf8-f8490ce9e54b.png)

**Comment by wwarriner** [comment]
I'm going to make a pull request so folks can test
