### ISSUE TITLE
Create the subdomain docs.rc.uab.edu to point at uabrc.github.io

### ISSUE THREAD

**Issue by jprorama** [uabrc/uabrc.github.io#330]
We need to create a subdomain configuration for our pages so that we can start to reference the URL https://docs.rc.uab.edu.  This will be more intuitive for users and position our content for better search results in Google, since the will see the content as part of the rc.uab.edu domain.

This appears to be a simple matter of defining the subdomain in the github pages configuration and then registering a CNAME record to point at the github.io site.  This CNAME can easily be requested from our domain operators.
```
docs.rc.uab.edu. CNAME uabrc.github.io
```

Here at the instructions for setting this value in the github.io pages project:

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

Note: the configuration in the github.io account comes before submitting the domain registration.

**Comment by jprorama** [comment]
Here is the setting that is needed:

![image](https://user-images.githubusercontent.com/192305/187506582-19f44ed8-2782-4e33-a0a6-541cdeb511c0.png)

Once in place we can register the CNAME in DNS.  Note, this won't prevent users from accessing the site at https://uabrc.github.io.  It simply makes it possible to also access it from https://docs.rc.uab.edu which can then become the preferred name in all our references.

**Comment by bjoyce3** [comment]
Looks like a simple domain name redirecting to the existing uabrc.github.io. 
- Won't break existing links because uabrc.github.io/ still resolves
- Gives us an easier name to remember (docs.rc.uab.edu)
I like it. Am I missing anything?

**Comment by jprorama** [comment]
You've got it right as far as I can tell.  I went to set the name in the project config but it gave me an error saying the name wasn't valid.  (Instructions said to do this before registering the domain.) Oh well, I've requested the CNAME registration so we do the next step from there.

**Comment by jprorama** [comment]
Adding some notes on configuration:

The correct order is update github.io pages project configuration per docs above and then register dns cname.  This avoids domain name hijacking issues.

However if your DNS service is slow to accept updates you need to get your CNAME in place first because saving the new domain in the project site is immediate. If your domain name isn't ready your site will redirect and fail to load at the new address.  Domain hijacking can be avoided with a [verified domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-for-your-organization-site) using a TXT record for the domain, which might be best to request in this circumstance. 

Once the above is in place, you update the redirect domain in the github io project.  This will verify your CNAME and then start the process of generating a Let's encrypt TLS cert for the new domain.

![image (12)](https://user-images.githubusercontent.com/192305/187778149-d3ea2013-11ed-48bb-ba16-fb96bfa6766f.png)


Once that's in place (can take some time) you can check the enforce HTTPS box and that will ensure your site is exclusively served via HTTPS. This causes references from the old github io https site to redirect to the new custom domain also at https.

![image (13)](https://user-images.githubusercontent.com/192305/187778288-ef8f7779-0220-4508-a8a7-9069f66de337.png)

**Comment by jprorama** [comment]
Leaving this here for the future.  These are the results that are currently active in Google in response to the search "uab cheaha", a reasonable starting point for users.  Looking forward to when the new domain name starts to be indexed instead. 
![image](https://user-images.githubusercontent.com/192305/188207398-66c691ca-837b-4387-bbb3-5584b36448c9.png)

**Comment by bjoyce3** [comment]
> Completed per discussion in slack!
> 
> For documentation purposes, to fully resolve all issues, we needed to check the "enforce https" box.

Did we check the "enforce https" box before this was closed?
