### ISSUE TITLE
Merging pull requests breaks custom domain setting

### ISSUE THREAD

**Issue by jprorama** [uabrc/uabrc.github.io#332]
It appears when pull requests are merged the custom domain name setting is removed from the project.  It is likely that we need to accommodate the considerations mentioned in [step 4 of the configuration process](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain). 

![image](https://user-images.githubusercontent.com/192305/188954655-0af7a96a-db29-4d1d-a981-6a1dd089f301.png)

In particular, we may need to [consider the publishing method for the site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site), i.e. branch or workflow action

There are also these [trouble shooting steps for custom domains ](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages) that may help.

**Comment by wwarriner** [comment]
Relevant, reading now: https://www.mkdocs.org/user-guide/deploying-your-docs/#custom-domains
