### ISSUE TITLE
Add Gitlab documentation

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#38]
- Github vs Gitlab and use cases for UAB researchers
- Login using XIAS accounts
- Login using BlazerIDs (only BlazerIDs! No uabmc as a warning)
- Suggestions for using and setting up projects/groups and how that might be useful for research groups getting started

**Comment by wwarriner** [comment]
Related to #14. Do we want a single GitLab page with all of this info? Or do we want a separate "gitlab account creation" page?

**Comment by jgordini** [comment]
[github_commands.md](https://github.com/uabrc/uabrc.github.io/files/8164164/github_commands.md)
Common Github Commands

Link to Gitlab Docs  
https://docs.gitlab.com/ee/gitlab-basics/#working-with-git-from-the-command-line

**Comment by wwarriner** [comment]
I think we've got this one under wraps once #433 is merged.
