### ISSUE TITLE
Relabel education/outreach page

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#401]
Education & Outreach -> Outreach & Training

Add/modify pages to include "training resources"
Add page: https://uab.campuslabs.com/engage/organization/informaticsclub
Note to scroll down to events, mention the "Code Chat Collab"

![image (1)](https://user-images.githubusercontent.com/6930772/199082918-064a34c2-78af-422d-9b28-3f52fa45afa3.png)

**Comment by bjoyce3** [comment]
This is the page to rename Training Resources: https://docs.rc.uab.edu/education/social_media/

Include other training (external) resources like:
- The Carpentries
- Rosalind Bioinformatics online training
- Codacademy (maybe? might be a for pay service now)
