### ISSUE TITLE
Information on logging into cloud.rc appears to be missing or doesn't include info on the required domain

### ISSUE THREAD

**Issue by jprorama** [uabrc/uabrc.github.io#408]
### What is inaccurate?

The introduction page doesn't show how to log into the dashboard. Part of the required info for the login is to list a domain.  Users have asked what the correct domain is.  It is "uab".  

We should add instructions showing how to log into the dashboard.

### Where is the inaccuracy?

https://docs.rc.uab.edu/uab_cloud/introduction/

**Comment by wwarriner** [comment]
I see we have no information at all on the login page. Definitely will add that once #387 is merged.
