### ISSUE TITLE
How to make your Cloud.RC Site public

### ISSUE THREAD

**Issue by jgordini** [uabrc/uabrc.github.io#413]
### What would you like to see added?

Would like a article detailing the process of gaining external access for Cloud.RC ips. 

Useful for external collaborators as well as public websites. 

May require going through UAB IT to set up TLS certificates, getting added to the DNS, having a firewall exception made. 

May need a knowledge base article set up. Checking to see if there is a related knowledge base article.

**Comment by jgordini** [comment]
Request form for Firewall Exception:
https://uabprod.service-now.com/service_portal?id=sc_cat_item&sys_id=daf70746374ce3c0daa253b543990e7f

Request form for SSL CRT:
https://www.uab.edu/it/uabcrt/

**Comment by jgordini** [comment]
UAB TLS Standards
https://uabprod.service-now.com/service_portal?sys_kb_id=22183f96dbf37b048d72f7441d96194a&id=kb_article_view&sysparm_rank=2&sysparm_tsqueryId=90aab4dc1bcb5d104ff06572604bcb6a

**Comment by jgordini** [comment]
All firewall exception requests will require approval by the college or departmental VLAN administrator prior to implementation. Not sure who that would be in your case.

**Comment by jgordini** [comment]
![Screen Shot 2022-11-04 at 1 02 56 PM](https://user-images.githubusercontent.com/92876980/200044841-707193c7-876c-49eb-b93e-3abf8c7c4159.png)

Also not sure which Firewall applys to Cloud.RC

**Comment by jgordini** [comment]
It seems like CloudRC would be a special case. Seeing if I can find a contact in Information Security to put you in touch with.

**Comment by jgordini** [comment]
Wasn't trying to be pushy. Just thinking about the process. Appreciate everyone.

**Comment by wwarriner** [comment]
Per JP (paraphrasing)

> Floating IPs in OpenStack are public IP addresses. By default, the UAB Border Firewall rules prevent external access to services hosted on OpenStack floating IP addresses. To request a firewall rule exception, please see (form elsewhere in this issue).
