### ISSUE TITLE
Clarify rclone basic usage

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#415]
```
At its most basic level all rclone commands involving transfers work like this:

`rclone command [flags] source:path destination:path`.

So if you want to swap the direction of transfer, swap the order of source and destination when you run the command.
```

Make sure to include the general structure, like above, and that you can swap direction by swapping places between `source:path` and `destination:path`

**Comment by jgordini** [comment]
here's an rclone tutorial that might be helpful. https://www.reddit.com/r/DataHoarder/comments/598pb2/tutorial_how_to_make_an_encrypted_acd_backup_on/

**Comment by wwarriner** [comment]
That's an interesting link, thanks @jgordini. It could come in handy if we want to make an rclone-as-backup-service tutorial. I'll keep it in my back pocket.

**Comment by jgordini** [comment]
I just didn’t see a section on encryption.
Might be helpful.

Step 4: Configure Encryption
There are two ways you can configure encryption. You can encrypt your cloud account at the top level, meaning all folders (that were uploaded with rclone) will have encrypted names.
You can also leave the top-level directory names decrypted for identification from the Web GUI, and any apps that the provider may have.. This has the disadvantage that you have to run this configuration process for every single folder in your cloud account. You can edit your config file manually if you have lots of folders to configure.

  1.  Run rclone config.
  2.  Press n.
  3.  Type a name for the encrypted container. For this tutorial, we will assume the name secret.
  4.  Press 5.
  5.  If you are encrypting the names of your top-level directories, just use remote: here.
If you are using decrypted top-level names, specify the path, for example remote:/Backups/, and keep in mind that you will need to create one of these containers for each top-level directory.

  1.  Type standard for encrypted file names.
  2.  Choose a passphrase or generate one. It is very important you remember your passphrase. If you forget it, your backups will be irretrievable and there is no reset process.
  3.  Choose a salt or generate one. This is optional but recommended, particularly with non-random passphrases. Same as with the passphrase, you must remember this salt.
  4.  Press y to confirm the details and q to close rclone.
Repeat these steps for as many encrypted containers as are needed for decrypted top-level directory names.


From: William Warriner ***@***.***>
Reply-To: "uabrc/uabrc.github.io" ***@***.***>
Date: Tuesday, November 29, 2022 at 11:58 AM
To: "uabrc/uabrc.github.io" ***@***.***>
Cc: Jeremy Gordinier ***@***.***>, Mention ***@***.***>
Subject: Re: [uabrc/uabrc.github.io] Clarify rclone basic usage (Issue #415)


That's an interesting link, thanks @jgordini<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjgordini&data=05%7C01%7Cjgordini%40uab.edu%7C010c1eb4e35c454fd9fe08dad2334dea%7Cd8999fe476af40b3b4351d8977abc08c%7C1%7C0%7C638053415056077031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NE2rmI8c1IG28FhRs1hJRSAX5hj40LuYbzEFAhpV7kw%3D&reserved=0>. It could come in handy if we want to make an rclone-as-backup-service tutorial. I'll keep it in my back pocket.
