### ISSUE TITLE
Assess What Pages 'Under Construction Admonitions' Exist On

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#417]
### What would you like to see added?

Assess pages with the "The information on this page is under construction and some of it may be obsolete. If you need additional clarifications in the meantime, please [contact us](https://docs.rc.uab.edu/#contact-us)." admonition and determine whether that's still accurate.

Example: https://docs.rc.uab.edu/data_management/storage/ has the admonition, but is it really true? We've updated that section quite extensively and leaving that at the top and potentially undermines researcher confidence in the docs.

**Comment by wwarriner** [comment]
List (and whether to keep/remove admonition)

Pages needing work:
- policies.md (please check)
- data_management/code_storage.md (don't have key purpose of page)
- education/case_studies.md (page needs formatting at the very least)
- grants/budgets.md (empty)
- grants/facilities.md (empty)
- grants/overview.md (empty)
- kubernetes/startup.md (stubby, on my todo list for the quarter)
- national_ci/nih.md (empty)
- national_ci/nsf_access.md (empty)
- national_ci/osg.md (empty)
- workflow_solutions/getting_software_with_git.md (empty, on my todo list eventually)
- workflow_solutions/shell.md (facl commands, on my todo list eventually)
- workflow_solutions/using_workflow_managers.md (on my todo list eventually)

Remove admonition:
- cheaha/software.md
- contributing/contributor_guide.md
- education/social_media.md
- uab_cloud/tutorial/instance.md (remove all)
- uab_cloud/snapshots.md (stubs for sharing snapshots)
- workflow_solutions/git.md (overview of git commands)

**Comment by wwarriner** [comment]
This is stable. I am comfortable with the current pages that are marked this way.
