### ISSUE TITLE
Add How to RC-MkDocs to RC-MkDocs

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#42]
- Recommended VS Code setup
- How to submit issues/recommendations
- How to submit edits/new material
- Links to Markdown + MkDocs reference materials: 
https://squidfunk.github.io/mkdocs-material/reference/admonitions/
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by wwarriner** [comment]
Resolved this with #251
