### ISSUE TITLE
Add 'Location' of storage to storage table

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#450]
### What would you like to see added?

1. Add a column with locations to the table of storage (Cheaha GPFS, nearline, LTS, etc). 
2. Add general overview diagram from Visio of RC ecosystem so researchers understand where the storage is located and what networks it travels over.

On page: https://docs.rc.uab.edu/data_management/storage/

**Comment by wwarriner** [comment]
Second point is related to #129

**Comment by wwarriner** [comment]
This has been handled, except for what is covered by #129, closing.
