### ISSUE TITLE
Update deadlines for $USER_SCRATCH

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#454]
### What is inaccurate?

The splash page dates need to get pushed back 5 weeks: ﻿﻿

January 13, 2023: Clean up of temp-scratch must be completed by all researchers. Access to temp-scratch will be removed for all researchers.
February 13, 2023: New $SCRATCH storage limited-retention policies will start.
To Be Determined: $USER_SCRATCH will point to /scratch/$USER

### Where is the inaccuracy?

https://gitlab.rc.uab.edu/rc/devops/-/issues/199#note_73264

**Comment by flakrat** [comment]
January 13, 2023: $USER_SCRATCH will point to /scratch/$USER
January 20, 2023: Clean up of temp-scratch must be completed by all researchers. Access to temp-scratch will be removed for all researchers.
February 13, 2023: New $SCRATCH storage limited-retention policies will start.
