### ISSUE TITLE
Mention File Encryption in the Docs and other Training

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#467]
The HIPAA security review noted that mentioning file encryption and how to do that for researchers would be useful.

Actual comment:
Users have the ability to encrypt files using tools provided by the UNIX (at the command line) but encryption is not widely used 

Recommendation:  Remind users about their ability to encrypt files using tools provided within the HPC environment.

**Comment by wwarriner** [comment]
I don't think there is a "built-in" encryption solution for files in Linux. `crypt` is an optional part of the POSIX standard. There are a number of third-party FOSS tools out there (literally dozens).

I think a brief mention of this possibility is worthwhile.

Subsection outline (wherever we put it):

1. Encryption is possible, and tools exist (`crypt` is an optional part of POSIX standard, lots of third party tools). We can work with PIs to ensure the proper tools are available on the system.
2. We are not responsible for vetting any encryption tools, nor for ensuring they comply with requirements relevant to your project, nor for ensuring ongoing compliance. Those are all PI responsibilities.
3. We are willing to work with PIs who have encryption needs to facilitate finding the right solutions and getting those solutions set up for use with our services.
4. If you have need for per-project encryption and are unsure where to start, please contact support.

**Comment by wwarriner** [comment]
Drives are encrypted at rest on our system, which enables "drive is stolen" type physical security. This is the best we can economically offer in terms of actual encryption for "every-day" HPC usage. There are Enterprise IT security reviews in place for other use cases, and researchers will need to practice good security hygiene generally. In short, we're doing what we can and this issue isn't really relevant for HPC use cases.
