### ISSUE TITLE
LTS/S3 policy "user" format for "Principal" block under `arn:aws:iam` may be inaccurate for Cheaha

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#470]
### What is inaccurate?

There is advice for "Principal" that format should go as `arn:aws:iam:::user/<blazerid>`. A researcher is reporting it should be `arn:aws:iam:::user/<blazerid>@uab.edu`. This suggests we may need to be sure of XIAS users would be granted access.

This may apply to all of the policy samples on the page. Rather than `bob` and `jane`, maybe `bob@uab.edu` and `jane@xias.collab.edu`.

### Where is the inaccuracy?

https://docs.rc.uab.edu/data_management/lts/sharing/

**Comment by mdefende** [comment]
This was an artifact from early LTS where original accounts (like mine) do not have the @uab.edu tag on them. After we started making lab accounts, individual accounts' full usernames are <blazerid>@uab.edu. So for some people it won't have the @uab.edu tag, that'll have to be the researchers' responsibility to know. I'll change the examples but add in a note about it
