### ISSUE TITLE
RStudio takes a very long time to start

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#53]
The job starts quickly, but the studio server tab has the spinning wheel of death and times out, or gives a 502/503 error (indicating the RStudio Server is overloaded).

@mdefende Could you relate your understanding of this topic here, and we can craft it into a brief admonition/section for OOD Interactive?

RITM0511239

**Comment by mdefende** [comment]
Yeah, generally these are a pretty easy fix. Just need to delete the .rstudio folder in the user home directory. I can add that in somewhere. A good FAQ as well

**Comment by wwarriner** [comment]
Yes definitely. Some of these issues are so non-specific it's tremendously helpful to have a differential diagnosis page or something :)
