### ISSUE TITLE
Rework account page

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#556]
### UAB Employees and Students

- Must have an active BlazerID
- Includes UAB Campus and UAB Medicine
- Includes Faculty, Staff, Postdocs, and Graduate Students
- Undergraduate student access is not available, apologies for any inconvenience.
- (link to broken-out page)

### External Collaborators 

- Must be sponsored by a UAB Employee.
- The sponsor assumes responsibility for any actions taken by the External collaborator on UAB systems.
- (link to XIAS index)

## What are my responsibilities?

- Be aware of and perform account holder responsibilities: #541 

## How do I create a Research Computing account?

This section would be part of `index.md` for the "Account Management" part of the docs. 

### Cheaha

- UAB Employees and Students: (break out page, put link here)
- External Collaborators: (link to page)

### Gitlab

- UAB Employees and Students: (link to page)
- External Collaborators: (link to page)

### Cloud.rc

- UAB Employees and Students: (link to page)
- External Collaborators: (link to page)

### Cheaha

- Duo (for Open OnDemand)
- UAB Employees and Students: BlazerID
- External Collaborators: XIAS

### Gitlab

- UAB Employees and Students: (link)
- External Collaborators: (link)

### Cloud.rc

- Duo + VPN
- UAB Employees and Students: (link)
- External Collaborators: (link)

## Important Links

- Duo (https://www.uab.edu/it/home/security/2-factor)
- VPN (requires Duo) (https://www.uab.edu/it/home/tech-solutions/network/vpn)

**Comment by flakrat** [comment]
Perhaps the following should be a Github issue by itself, but starting the convo here as it relates to the troubleshooting comment above. Here's a recent comment added to a support ticket:
> In order to pick up the new group membership they will have to do the following because they currently are SSH'd into Cheaha and have an active Open OnDemand session via https://rc.uab.edu :
> * Exit out of any SSH connections they have to cheaha.rc.uab.edu and log back in
> * In Open OnDemand (https://rc.uab.edu) Click the <Develop> menu in the upper right corner, then click Restart Web Server
> * Restart any OnDemand virtual desktops

Q: What does a user need to do when added to a group on Cheaha?
A: 
- Do they have any processes / connections on cheaha.rc.uab.edu?
  - If they have active SSH sessions, they will need to exit out and log back in
  - Additional complication, if they have active Tmux/Screen sessions, they will need to terminate those, log out, log back in and start Tmux. This can be painful but can be helped with Tmux plugins that continually save the Tmux session state and allow it to be restored.

I use a combo of the following 2 plugins. However, I found a more modern Tmux Session Manager, [TmuxP](https://github.com/tmux-python/tmuxp) that I may switch to [TmuxP HowTo](https://betterprogramming.pub/how-to-use-tmuxp-to-manage-your-tmux-session-614b6d42d6b6)
    - [Tmux Resurrect](https://github.com/tmux-plugins/tmux-resurrect)
    - [Continuum](https://github.com/tmux-plugins/tmux-continuum)
- Do they have an active Open OnDemand session?
  - In Open OnDemand (https://rc.uab.edu) Click the <Develop> menu in the upper right corner, then click Restart Web Server
- Do they have one or more OOD HPC Desktops running?
  - Terminate the desktops and start new ones
