### ISSUE TITLE
Fix CUDA Toolkit section

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#563]
### What is inaccurate?

Researchers have to ensure _both_ `cuda*/toolkit` and `cuDNN` modules are loaded.

### Where is the inaccuracy?

https://docs.rc.uab.edu/cheaha/slurm/gpu/#cuda-toolkit

**Comment by wwarriner** [comment]
Also fix the email link while we're in there!

**Comment by mdefende** [comment]
We can add a subsection about cuDNN since cuDNN is only necessary for DNN models. Other models, like XGBoost, would need the cuda toolkit but not cuDNN.
