### ISSUE TITLE
Curate list of LinkedIn Learning courses we think may be helpful

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#576]
### What would you like to see added?

Add list of courses and links we think may be helpful/relevant to our services and researchers here: https://docs.rc.uab.edu/education/training_resources/#internal-resources

**Comment by iam4tune** [comment]
I feel that we do not necessarily have to include a list of courses from LinkedIn Learning. LinkedIn Learning has a really good interface for searching courses, and a search for a topic or interest would usually show a list of courses an intended user can watch/learn from.

**Comment by wwarriner** [comment]
I agree with Fortune. My thoughts: adding links to specific courses would only make sense if we could vouch for the content in some way, i.e., have done the course. The courses will change over time. And linking to search results, while possible in a clean way, doesn't add much value.
