### ISSUE TITLE
Beware of `module save` becoming the user's modules-loaded-by-default

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#669]
### What would you like to see added?

See here for instructions on how this can happen <https://lmod.readthedocs.io/en/latest/010_user.html#user-collections>.

If a researcher uses `module save $name` at any point, the currently loaded set of modules is saved as a user collection in a configuration file used by lmod, with the name `$name`. Collections can be loaded with `module restore $name`, and listed with `module savelist`.

If the command `module save` is given with no `$name`, then it is saved with the name `default` and loaded as part of the lmod startup process. Every shell and terminal will now have a command equivalent to `module restore default` run, restoring those saved default modules. This is a new way for researchers to have issues starting OOD jobs, including HPC Desktop jobs, if the modules loaded include Anaconda or other modules that may interfere with OOD jobs functioning.

To disable any module collection, including the default collection, use `module disable $name` or `module disable default`. To delete a collection, navigate to `~/lmod.d/` and delete the file named `$name`. If it had previously been disabled, it will have a `~` character at the end like `$name~`.

**Comment by wwarriner** [comment]
Related to this FAQ entry: https://ask.cyberinfrastructure.org/t/why-do-i-get-an-error-when-launching-an-open-ondemand-hpc-interactive-session/2496/2

Consider creating a sibling entry on ask.ci

**Comment by Premas** [comment]
Update https://docs.rc.uab.edu/cheaha/software/modules/
