### ISSUE TITLE
Rearrange Anaconda content on docs

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#681]
Most information is here: https://docs.rc.uab.edu/workflow_solutions/using_anaconda
Some information is here: https://docs.rc.uab.edu/cheaha/software/software/#anaconda-on-cheaha

## Collecting Cloud.rc specific information

- [x] Move this: https://docs.rc.uab.edu/workflow_solutions/using_anaconda/#what-is-my-best-solution-for-installing-anaconda
- [x] To here: https://docs.rc.uab.edu/uab_cloud/installing_software/#installing-software
    - [x] Note we have this already! https://docs.rc.uab.edu/uab_cloud/installing_software/#installing-miniconda
    - [x] Add info on how to enable `libmamba` to get faster installs (https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community) 
- [x] And crosslink "how to use Anaconda" within the result (https://docs.rc.uab.edu/workflow_solutions/using_anaconda/#using-anaconda)

## Collecting Cheaha specific information

- [x] This appears to already be taken care of here: https://docs.rc.uab.edu/cheaha/software/software/. Consider moving the admonitions elsewhere in the same page.

## Remove obsolete information

Mamba is now part of Anaconda3 and always will be, so references to Mamba are now irrelevant. We don't need to maintain two separate package managers that do exactly the same thing.

- [x] https://docs.rc.uab.edu/cheaha/software/software/#speedups-using-mamba
- [x] https://docs.rc.uab.edu/workflow_solutions/using_anaconda/#speeding-things-up-with-mamba

## New content

- [ ] Content in #567 would go somewhere (start of?) https://docs.rc.uab.edu/workflow_solutions/using_anaconda/#using-anaconda
- [x] Content in #659 would go in a separate sibling page, and we can create a fold-out perhaps with an index.md?

**Comment by wwarriner** [comment]
We can start working after #659 is merged.

**Comment by iam4tune** [comment]
Due to recent changes with Anaconda, libmamba comes pre-installed. So I will be deleting any content related to libmamba.

**Comment by wwarriner** [comment]
Good idea. Most researchers aren't going to need to know, and the only impacts should be positive. Early on (July thru January) I encountered some cache-related issues, but haven't in the last few months.
