### ISSUE TITLE
Update documentation links on other platforms

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#69]
Update to include new documentation links:
- UAB RC website "We're here to help you"
- rc.uab.edu message of the day in OOD (code here: https://github.com/wwarriner/slurm_status_tools)
-- Include spaces for the table to separate columns correctly (https://github.com/uabrc/CRI_XCBC/issues/85)
-- Include number of GPUs on partitions
![image](https://user-images.githubusercontent.com/11023317/153905233-5d83fca0-ab50-4eb6-93d9-ce9d5568e173.png)
-- Add CPUs per node and/or remove nodes (leave nodes per user)
-- Usable memory per node
- Terminal Message of the Day
-- Get access to that
- Update Cheaha and Cloud registration messages with new documentation and table for partitions

**Comment by wwarriner** [comment]
Taking a closer look, these are all complete.
