### ISSUE TITLE
How do I fix a terminal that looks like `bash-4.2$` instead of the usual `[$USER@login004]`?

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#697]
### What would you like to see added?

This can happen when your `.bashrc` or `.bash_profile` are missing or corrupted. If you have any changes in those files you wish to keep, rename them first to back them up, something like `mv .bashrc .bashrc.old`, for example.

To fix the issue, open a terminal and navigate to your home directory with `cd ~`. Run the command `cp /etc/skel/.bash* ~/` to copy over the default versions of those same files. Doing this will clobber, or remove, any changes you may have made, so be sure to make a backup first if you wish to keep any changes.

Exit the terminal and start a new one for the changes to take effect.

**Comment by Premas** [comment]
https://docs.rc.uab.edu/cheaha/getting_started/
