### ISSUE TITLE
Broken links in storage table on storage page.

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#741]
### What happened?

There are broken links in the CSV table at https://docs.rc.uab.edu/data_management/storage/

These are broken:

- User Data and Home Directories
- Project Directories
- Global Scratch

### What should happen instead?

Links should take me to the correct location.

**Comment by bdu-birhanu** [comment]
It would be good to consider creating separate pages for 'Project Directories' and also for 'User Data and  Home Directories', similar to the one we have for LTS.
