### ISSUE TITLE
Instructions for creating guest collections in globus connect perrsonal endpoints

### ISSUE THREAD

**Issue by mdefende** [uabrc/uabrc.github.io#750]
### What would you like to see added?

Some users want to be able to share data from local workstations and personal machines with other Globus users without having to move it to Cheaha first. This is possible through Globus connect Personal (GCP) endpoints, but some steps are necessary for setup.

### Being added to the UAB Globus group

They need to be added to the [University of Alabama at Birmingham (HA)](https://app.globus.org/groups/d3ae2bbe-381c-11e8-986b-0a27e80744b0) Globus group. No one is added by default, they must apply through the Globus interface and wait for one of the group admins to accept their application.

### Make Directories Shareable

On the local machine, you need to enable sharing for the given directories you want to share. The process is different for different OS listed below.

#### Windows

Full instructions for Windows configurations can be found in the [Globus Docs](https://docs.globus.org/globus-connect-personal/install/windows/#configuration).

0. Before trying to make any edits, make sure GCP is running.
1. Right-click the GCP icon in the taskbar
2. Select `Options...`
3. In the window that appears, make sure you're in the `Access` subwindow. 
4. Add the path you want to share to the list by clicking the `+` button. Make sure the `Shareable` option is selected

#### Linux

Full instructions for Linux path configuration can be found in the [Globus Docs](https://docs.globus.org/globus-connect-personal/install/linux/#config-paths).

1. If using a default installation for GCP in Linux, open the `$HOME/.globusonline/lta/config-paths` file in your favorite text editor.
    1. If you altered the installation path or changed where the `.globusonline` directory is stored, locate it.
2. In a new line, add the following line: `<path/to/share>,1,1`. 
    1. `1,1` means the directory is shareable and writable, respectively. If you want the collection to be only readable, the line should be `<path/to/share>,1,0` instead

#### Mac

Full instructions for Mac configuration can be found on [Globus Docs](https://docs.globus.org/globus-connect-personal/install/mac/#configuration).

0. Make sure GCP is running
1. Click the GCP icon in the taskbar
2. Select `Preferences...`
3. Switch to the `Access` tab in the window that appears.
4. Add the path you want to share to the list by clicking the `+` button. Make sure the `Shareable` option is selected

A note about directory paths, if you are wanting to share multiple directories as different collections (i.e. distributing data from a common location to different groups), you do not need to add each individual directory. Instead only add the parent folder for all of the directories you want to share and make it sharable. All subdirectories inherit the sharable trait from the parent and can be made into their own Guest collections and shared with distinct groups.

### Change the GCP Collection Subscription

Once you are added to the UAB Globus group, you can link your GCP collection with the UAB license. Do the following:

1. Login to [globus.org](https://globus.org) using your UAB credentials.
2. Go to Collections in the lefthand menubar.
3. Select your GCP collection.
4. Select Edit Subscription Status.
5. Change `None` to `University of Alabama at Birmingham (HA)` and then Save. You may be asked to reauthenticate.

### Adding a Guest Collection

Can reference our [current docs](https://docs.rc.uab.edu/data_management/transfer/globus/#creating-a-shared-collection) for how to create a guest collection within the GCP endpoint

**Comment by wwarriner** [comment]
Let's also add they they'll need to create a Support Request via support@listserv.uab.edu to help bring it to our attention through existing support channels.

**Comment by wwarriner** [comment]
Related to internal procedures: https://github.com/uabrc/devops-docs/issues/53

**Comment by wwarriner** [comment]
I believe this has been addressed by our collective efforts on Globus tutorials.
