### ISSUE TITLE
Update broken URLs for Sprint 24-16

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#773]
### What is inaccurate?

In #791:

- [x] Change all IT policy URLs to start with https://secure4.compliancebridge.com/uab/portal
   - Formerly started with "secure2" not "secure4".
- [x] Change OSG (Open ScienceGrid) URL to: https://osg-htc.org/
- [x] Change Docker links to "docs.docker.com/reference" instead of "docs.docker.com/engine/reference"
- [x] Change "docs.globus.org" URLs to have a trailing slash

In #790:

- [x] Change https://rclone.org/install/#macos-installation-with-brew to https://rclone.org/install/#macos-brew
- [x] Change https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701 to https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-us&gl=US
- [x] Change Singularity docs links from sylabs.io to docs.sylabs.io
- [x] Some docs.github.com and docs.gitlab.com URLs and anchors have changed.
- [x] gitlab.org moved to about.gitlab.com

In #798:

- [x] Change `support.rstudio.com` to `support.posit.co`. There may be more details, so ensure the URL still works.
- [x] Expand stackexchange short URLs (https://stackoverflow.com/a/57369284) to their full form (https://stackoverflow.com/questions/56839307/adding-git-bash-to-the-new-windows-terminal/57369284#57369284)
- [x] Change docs.microsoft.com changed to learn.microsoft.com. Double check the URLs work

### Where is the inaccuracy?

Use ctrl+shift+f to find the original URLs or fragments in all docs pages in VSCode.

**Comment by Premas** [comment]
I can work on fixing these issues

Change all IT policy URLs to start with https://secure4.compliancebridge.com/uab/portal
Formerly started with "secure2" not "secure4".
Change OSG (Open ScienceGrid) URL to: https://osg-htc.org/
Change Docker links to "docs.docker.com/reference" instead of "docs.docker.com/engine/reference"
Change "docs.globus.org" URLs to have a trailing slash

**Comment by iam4tune** [comment]
I will work on the following links

* Change https://rclone.org/install/#macos-installation-with-brew to https://rclone.org/install/#macos-brew
* Expand stackexchange short URLs (https://stackoverflow.com/a/57369284) to their full form (https://stackoverflow.com/questions/56839307/adding-git-bash-to-the-new-windows-terminal/57369284#57369284)
* Change https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701 to https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-us&gl=US
* Change Singularity docs links from sylabs.io to docs.sylabs.io
* Some docs.github.com and docs.gitlab.com URLs and anchors have changed.
* gitlab.org moved to about.gitlab.com

**Comment by bdu-birhanu** [comment]
I will work on editing the URLs listed below.:
-  Change support.rstudio.com to support.posit.co. There may be more details, so ensure the URL still works.
-  Expand stackexchange short URLs (https://stackoverflow.com/a/57369284) to their full form (https://stackoverflow.com/questions/56839307/adding-git-bash-to-the-new-windows-terminal/57369284#57369284)
- Change docs.microsoft.com changed to learn.microsoft.com. Double check the URLs work

**Comment by bdu-birhanu** [comment]
> I will work on editing the URLs listed below:
> 
> * Change support.rstudio.com to support.posit.co. There may be more details, so ensure the URL still works.
> * Expand stackexchange short URLs (https://stackoverflow.com/a/57369284) to their full form (https://stackoverflow.com/questions/56839307/adding-git-bash-to-the-new-windows-terminal/57369284#57369284)
> * Change docs.microsoft.com changed to learn.microsoft.com. Double check the URLs work

When I selected this part, I didn't realize it had already been addressed. Prema has resolved it in #798. Thank you.
