### ISSUE TITLE
Resolve Package Conflict with libffi, tk, and xz in `mkdocs` Build

### ISSUE THREAD

**Issue by Premas** [uabrc/uabrc.github.io#788]
### What would you like to see added?

We observed a package conflict issue with `libffi`, `tk`, and `xz` while building `mkdocs` environment on macOS ARM64.

Installing the following versions resolved the issue:

libffi=3.4.2
tk=8.6.13
xz=5.2.6

We need to identify and test compatible versions of these packages for cross-platform builds.

**Comment by wwarriner** [comment]
This turned out to be related to the `anaconda` channel having different versions available than `conda-forge`.
