### ISSUE TITLE
Globus Tutorials

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#800]
We have been asked to develop clearer, more detailed tutorials for working with Globus. There are two separate overarching tutorials needed. They should address the following questions. They should be in separate files. Some cross-linking is expected and noted below. Bolded parts are the current priority.

We are going to use this as an exercise of our GitHub collaboration abilities. The file names to use are given below. Put both files in `/docs/data_management/tutorial/*.md`. Each of us will work on part of this project, and we will integrate them together later.

1. A tutorial for individual researchers (students, staff, Core customers, etc.). This file will be called `globus_individual_tutorial.md`.
    - **What is Globus, and why would I use it?**
    - **How do I get onto Globus?**
    - **How do I find collections shared with me?**
    - How do I search for collections by name?
    - How do I transfer data from a shared collection to my project directory on Cheaha?
    - How do I transfer data from a shared collection to my group's LTS allocation?
    - How do I transfer data between LTS and Cheaha?

3. A tutorial for research managers (Lab PIs, Core directores, and their management staff). This file will be called `globus_group_tutorial.md`.
    - **What is Globus, and why would I use it? (link to above, don't duplicate)**
    - **How do I get onto Globus? (link to above, don't duplicate)**
    - **How do I install Globus Connect Personal?**
        - Windows
        - MacOS
    - **How do I configure the GCP endpoint to share specific folders?**
        - Windows
        - MacOS
    - **What prerequisites do I need before I can share a GCP endpoint?**
        - Joining the UAB (HA) subscription group.
    - **How do I configure a shared collection on my GCP endpoint?**
    - **How do I share a collection with a collaborator?**
    
Please make note of which parts you intend to work on in the comments below. I've got images stored here that tell some of the stories above: https://uab.app.box.com/folder/282177791476. Do not include the images in your work yet, until we've cleaned them up. Just write the text for now.

**Comment by wwarriner** [comment]
See #785 for a bit more info on shared collections.

**Comment by iam4tune** [comment]
I will take section 2, of this tutorial.

**Comment by bdu-birhanu** [comment]
I will cover the first **four bullet points** of section 1.

**Comment by Premas** [comment]
I will take the rest of Section 1.
