### ISSUE TITLE
URL requiring update due to redirections

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#826]
### What is inaccurate?

|docs page|current url|change to this url|
| - | - | - |
|uab_cloud/installing_software.md|https://docs.sylabs.io/docs/|https://sylabs.io/docs/|
|workflow_solutions/git.md|https://docs.github.com/en/get-started/quickstart/fork-a-repo|https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo|
|workflow_solutions/git_collaboration.md|https://docs.github.com/en/get-started/quickstart/create-a-repo|https://docs.github.com/en/repositories/creating-and-managing-repositories/quickstart-for-repositories|
|workflow_solutions/git_collaboration.md|https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account|https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github|

Make sure the new link matches the content on our docs!

### Where is the inaccuracy?

See table above.

**Comment by iam4tune** [comment]
I will make these edits.
