### ISSUE TITLE
Cloud docs

### ISSUE THREAD

**Issue by jgordini** [uabrc/uabrc.github.io#96]
In the router section if you don't connect the router to the gateway it will not show you any ports when you create an instance. 

on mac when you download the ssh certificate it's exension is crt. It can be renamed to pem and used but it is a little confusing if you are not familiar with setting up ssh. 

Seems like the access levels for cloud instances are a little generous. 

Docs are great. Was able to set up a instance very easily. 

Nice to haves would be some server setup documentation for those who want to create one on their instance. Would be also good to encourge instance users to setup secure applications. 

Example documenation found here. 
https://serversforhackers.com/s/start-here

https://serversforhackers.com/t/beginners

**Comment by jgordini** [comment]
I will try and reinstall the instance and screenshot the issues. So I can provide better notes.

**Comment by jgordini** [comment]
https://uabrc.github.io/uab_cloud/instance_setup_basic/

Shouldn't these be reversed. 

Select "Yes" or "No" under "Delete Volume on Instance Delete"

"Yes" is a good choice if the OS volume will be reused.
"No" is a good choice if you don't care about reusing the OS.

**Comment by wwarriner** [comment]
I'm flipping the values on the last one just now.

I want to clarify on the other issues. Can you provide screenshots of them in action?

**Comment by jgordini** [comment]
![Screen Shot 2022-03-29
![Screen Shot 2022-03-29 at 4 37 00 PM](https://user-images.githubusercontent.com/92876980/160711529-2a16e3a1-e05b-47a4-9762-6fac3a59090d.png)
 at 4 36 43 PM](https://user-images.githubusercontent.com/92876980/160711511-a41ab880-fdfa-4085-bfcb-6b4fd3af8df6.png)

**Comment by jgordini** [comment]
![Screen Shot 2022-03-29 at 4 37 00 PM](https://user-images.githubusercontent.com/92876980/160711582-67e4d267-fc23-4099-ac5c-62b6937832f1.png)

**Comment by jgordini** [comment]
not sure if I can replicate the router issue.

**Comment by wwarriner** [comment]
I wonder if the router issue was ephemeral while we were still configuring things?

Thank you for the shots. I'm going to rewrite some of the descriptions to get away from "pem" and make it a bit more generic.

**Comment by jgordini** [comment]
Could be took a while to get to that screen. So not sure if I can replicate again. Sorry for any hassle.

From: William Warriner ***@***.***>
Date: Tuesday, March 29, 2022 at 4:53 PM
To: uabrc/uabrc.github.io ***@***.***>
Cc: Gordinier, Jeremy ***@***.***>, Author ***@***.***>
Subject: Re: [uabrc/uabrc.github.io] Cloud docs (Issue #96)

I wonder if the router issue was ephemeral while we were still configuring things?

Thank you for the shots. I'm going to rewrite some of the descriptions to get away from "pem" and make it a bit more generic.
