### ISSUE TITLE
Admonitions broken

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#98]
I think a number of the admonitions are broken across the site. Will need to go through and possibly rethink the way we fix linting. We may need to use the fenced style of "ignore this warning", rather than the "ignore next line" style.

Will need to update the contributor guide (currently in the readme).

**Comment by jgordini** [comment]
Could you use block quotes instead of notes?

**Comment by wwarriner** [comment]
They've been broken due to the way we'd been handling linting. Wrapping the entire admonition in appropriate markdown lint "ignore this" comments fixes the issue, and the admonitions are formatted correctly. They're supposed to look like on this page: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types

These will be fixed, and the readme will be updated to mention this, as part of #99

**Comment by jgordini** [comment]
That makes sense. Fix Looks good.
